"""
Database models 统一导出入口。

⚠️ 顺序敏感：被关系引用的 model 必须先导入
    - Project 要在 TestEnvironment 之前
    - Module / TestCase / TestStep 要有明确的相互可见性
    - 所有 model 都必须在 Alembic autogenerate 扫描前被 import 一次
"""

# ============ 业务主体 ============
from .project import (
    Project,
    PROJECT_STACK_API,
    PROJECT_STACK_WEB,
    PROJECT_STACK_ANDROID,
    PROJECT_STACK_IOS,
    PROJECT_STACK_FUNCTIONAL,
    ALL_PROJECT_STACKS,
)
from .module import Module
from .user import User
from .user_session import UserSession
from .role import (
    Role,
    user_roles,
    ROLE_ADMIN,
    ROLE_DEV,
    ROLE_TEST,
    ROLE_PM,
    ROLE_UI,
    ROLE_OPS,
    ALL_ROLE_CODES,
)

from .task import (
    Task,
    TASK_TYPE_DEV,
    TASK_TYPE_TEST,
    TASK_TYPE_UI_REVIEW,
    TASK_TYPE_PM_REVIEW,
    TASK_TYPE_BUG,
    ALL_TASK_TYPES,
    TASK_STATUS_PENDING,
    TASK_STATUS_DEV_DOING,
    TASK_STATUS_DEV_DONE,
    TASK_STATUS_TEST_DOING,
    TASK_STATUS_PASSED,
    TASK_STATUS_FAILED,
    TASK_STATUS_CLOSED,
    ALL_TASK_STATUSES,
    BUG_SEVERITY_P0,
    BUG_SEVERITY_P1,
    BUG_SEVERITY_P2,
    BUG_SEVERITY_P3,
    ALL_BUG_SEVERITIES,
)

from .version_test_summary import VersionTestSummary

# ============ 用例 & 步骤（v2 核心） ============
from .test_case import (
    TestCase,
    CASE_TYPE_API,
    CASE_TYPE_ANDROID,
    CASE_TYPE_IOS,
    CASE_TYPE_WEB,
    CASE_TYPE_MIXED,
    CASE_TYPE_FUNCTIONAL,
    ALL_CASE_TYPES,
    APP_CASE_TYPES,
    AUTOMATED_CASE_TYPES,
)
from .functional_case_run import (
    FunctionalCaseRun,
    RUN_STATUS_PASSED,
    RUN_STATUS_FAILED,
    RUN_STATUS_BLOCKED,
    RUN_STATUS_NA,
    RUN_STATUS_PENDING,
    ALL_RUN_STATUSES,
)
from .functional_case_edit_history import (
    FunctionalCaseEditHistory,
    EDIT_ACTION_CREATE,
    EDIT_ACTION_UPDATE,
    EDIT_ACTION_DELETE,
    ALL_EDIT_ACTIONS,
)
from .api_case_edit_history import ApiCaseEditHistory
from .edit_operation import (
    EditOperationBatch,
    EditOperationEvent,
    ENTITY_TYPE_REQUIREMENT,
    ENTITY_TYPE_TEST_CASE,
    ROLLBACK_STATUS_NONE,
    ROLLBACK_STATUS_PARTIAL,
    ROLLBACK_STATUS_FULL,
    ROLLBACK_STATUS_ROLLED_BACK,
)
from .test_step import (
    TestStep,
    # 步骤类型常量，方便业务代码直接引用
    STEP_TYPE_HTTP_REQUEST,
    STEP_TYPE_SQL_QUERY,
    STEP_TYPE_SCRIPT,
    STEP_TYPE_APP_LAUNCH,
    STEP_TYPE_APP_CLOSE,
    STEP_TYPE_APP_TAP,
    STEP_TYPE_APP_INPUT,
    STEP_TYPE_APP_SWIPE,
    STEP_TYPE_APP_PRESS,
    STEP_TYPE_APP_WAIT,
    STEP_TYPE_APP_SCREENSHOT,
    STEP_TYPE_APP_BACK,
    STEP_TYPE_WEB_GOTO,
    STEP_TYPE_WEB_CLICK,
    STEP_TYPE_WEB_INPUT,
    STEP_TYPE_WEB_SELECT,
    STEP_TYPE_WEB_WAIT,
    STEP_TYPE_ASSERT,
    STEP_TYPE_SLEEP,
    ALL_STEP_TYPES,
)

# ============ 环境 & 变量（v2 新增） ============
from .test_environment import TestEnvironment
from .test_variable import TestVariable

# ============ 设备（v2 新增，App 专用） ============
from .device import (
    Device,
    DEVICE_STATUS_IDLE,
    DEVICE_STATUS_BUSY,
    DEVICE_STATUS_OFFLINE,
)

# ============ App 安装包仓库（v2 新增，App 包管理 / 选择器用） ============
from .app_package import AppPackage

# ============ 报告 ============
from .test_report import TestReport
from .test_step_report import TestStepReport
# from .hook_test_report import HookTestReport
# from .hook_test_step_report import HookTestStepReport

# ============ 配置 ============
from .config_store import ConfigStore
from .script_store import (
    ScriptStore,
    SCRIPT_KIND_FUNCTION,
    SCRIPT_KIND_CRYPTO_REQUEST,
    SCRIPT_KIND_CRYPTO_RESPONSE,
    ALL_SCRIPT_KINDS,
)
from .module_outline import (
    ModuleOutline,
    ModuleOutlinePoint,
    OUTLINE_POINT_COVERED,
    OUTLINE_POINT_GAP,
    OUTLINE_POINT_OBSOLETE,
    ALL_OUTLINE_POINT_STATUSES,
    OUTLINE_POINT_SOURCE_AI,
    OUTLINE_POINT_SOURCE_MANUAL,
    ALL_OUTLINE_POINT_SOURCES,
)
from .ai_case_flag import (
    AiCaseFlag,
    AI_FLAG_MANUAL_FIX,
    AI_FLAG_INTERFACE_DEFECT,
    AI_FLAG_ENVIRONMENT,
    AI_FLAG_AI_FIXED,
    ALL_AI_FLAG_TYPES,
    AI_FLAG_STATUS_ACTIVE,
    AI_FLAG_STATUS_CLEARED,
    AI_FLAG_STATUS_AUTO_CLEARED,
    AI_FLAG_STATUS_SUPERSEDED,
    ALL_AI_FLAG_STATUSES,
    AI_FLAG_REASON_MANUALLY_FIXED,
    AI_FLAG_REASON_MISJUDGED,
    AI_FLAG_REASON_EXTERNAL_FIXED,
    AI_FLAG_REASON_WONT_FIX,
    ALL_AI_FLAG_REASONS,
)

# ============ AI 任务 / 需求（AI 模块）============
from .ai_run import (
    AiRun,
    AI_RUN_STATUS_PENDING,
    AI_RUN_STATUS_RUNNING,
    AI_RUN_STATUS_SUCCESS,
    AI_RUN_STATUS_FAILED,
    AI_RUN_STATUS_CANCELLED,
    ALL_AI_RUN_STATUSES,
    AI_FEATURE_REQUIREMENT_PARSE,
    AI_FEATURE_TEST_PLAN,
    AI_FEATURE_FUNCTIONAL_CASE_GEN,
    AI_FEATURE_FUNCTIONAL_CASE_ENHANCE,
    AI_FEATURE_FUNCTIONAL_CASE_REVIEW,
    AI_FEATURE_API_CASE_GEN,
    AI_FEATURE_REPORT_SUMMARY,
    AI_FEATURE_TEST_RESULT_ANALYSIS,
    AI_FEATURE_FUNCTIONAL_TO_AUTO,
    AI_FEATURE_LOAD_PLAN_GEN,
    AI_FEATURE_BUG_FIX,
    AI_FEATURE_API_REPORT_FIX,
)
from .requirement import (
    Requirement,
    REQUIREMENT_STATUS_DRAFT,
    REQUIREMENT_STATUS_APPROVED,
    REQUIREMENT_STATUS_ARCHIVED,
    ALL_REQUIREMENT_STATUSES,
    REQUIREMENT_SOURCE_MANUAL,
    REQUIREMENT_SOURCE_AI,
    REQUIREMENT_SYSTEM_STATUS_APPROVED,
    REQUIREMENT_SYSTEM_STATUS_DEVELOPING,
    REQUIREMENT_SYSTEM_STATUS_TESTING,
    REQUIREMENT_SYSTEM_STATUS_READY_TO_RELEASE,
    REQUIREMENT_SYSTEM_STATUS_PM_REVIEW,
    REQUIREMENT_SYSTEM_STATUS_DONE,
    ALL_REQUIREMENT_SYSTEM_STATUSES,
    REQUIREMENT_SYSTEM_STATUS_ORDER,
    REQUIREMENT_SYSTEM_STATUS_TASK_DRIVEN,
    REQUIREMENT_BUSINESS_STATUS_APPROVED,
    REQUIREMENT_BUSINESS_STATUS_ACCEPTED,
    REQUIREMENT_BUSINESS_STATUS_RELEASED,
    ALL_REQUIREMENT_BUSINESS_STATUSES,
)
from .requirement_assignee import (
    RequirementAssignee,
    REQUIREMENT_ASSIGNEE_ROLE_DEV,
    REQUIREMENT_ASSIGNEE_ROLE_TEST,
    REQUIREMENT_ASSIGNEE_ROLE_PM,
    REQUIREMENT_ASSIGNEE_ROLE_UI,
    ALL_REQUIREMENT_ASSIGNEE_ROLES,
)
from .requirement_version_history import (
    RequirementVersionHistory,
    REQUIREMENT_VERSION_ACTION_PLAN,
    REQUIREMENT_VERSION_ACTION_MOVE,
    REQUIREMENT_VERSION_ACTION_REMOVE,
    ALL_REQUIREMENT_VERSION_ACTIONS,
)
from .requirement_edit_history import (
    RequirementEditHistory,
)
from .attachment import (
    Attachment,
    ATTACHMENT_KIND_LINK,
    ATTACHMENT_KIND_FILE,
    ALL_ATTACHMENT_KINDS,
)
from .requirement_analysis_document import (
    RequirementAnalysisDocument,
    RequirementAnalysisVersion,
)
from .ai_case_draft import (
    AiCaseDraft,
    AI_CASE_DRAFT_STATUS_PENDING,
    AI_CASE_DRAFT_STATUS_ACCEPTED,
    AI_CASE_DRAFT_STATUS_REJECTED,
    ALL_AI_CASE_DRAFT_STATUSES,
)
# ============ AI Studio M1：对话写需求 + AI 下发编码 =====================
from .ai_dialogue_session import (
    AiDialogueSession,
    AI_DIALOGUE_STATUS_ACTIVE,
    AI_DIALOGUE_STATUS_FINALIZED,
    AI_DIALOGUE_STATUS_ABANDONED,
    ALL_AI_DIALOGUE_STATUSES,
)
from .ai_requirement_draft import (
    AiRequirementDraft,
    AI_REQ_DRAFT_STATUS_PENDING,
    AI_REQ_DRAFT_STATUS_COMMITTED,
    AI_REQ_DRAFT_STATUS_REJECTED,
    ALL_AI_REQ_DRAFT_STATUSES,
)
from .coding_task import (
    CodingTask,
    CODING_TASK_STATUS_QUEUED,
    CODING_TASK_STATUS_INDEXING,
    CODING_TASK_STATUS_GENERATING,
    CODING_TASK_STATUS_APPLIED,
    CODING_TASK_STATUS_FAILED,
    CODING_TASK_STATUS_COMMITTED,
    CODING_TASK_STATUS_PUSHED,
    CODING_TASK_STATUS_REJECTED,
    ALL_CODING_TASK_STATUSES,
)
from .code_chunk import CodeChunk, DEFAULT_EMBEDDING_DIM
from .test_plan import (
    TestPlan,
    TEST_PLAN_STATUS_DRAFT,
    TEST_PLAN_STATUS_PUBLISHED,
    TEST_PLAN_STATUS_ARCHIVED,
    ALL_TEST_PLAN_STATUSES,
    TEST_PLAN_SOURCE_MANUAL,
    TEST_PLAN_SOURCE_AI,
)
from .project_context import (
    ProjectContext,
    RequirementAnalysis,
    CONTEXT_TYPE_BUSINESS_RULE,
    CONTEXT_TYPE_DATA_MODEL,
    CONTEXT_TYPE_API_CONTRACT,
    CONTEXT_TYPE_ARCHITECTURE,
    CONTEXT_TYPE_TERM_DEFINITION,
    CONTEXT_TYPE_REQUIREMENT,
    CONTEXT_TYPE_CONSTRAINT,
    CONTEXT_TYPE_USER_SCENARIO,
    CONTEXT_TYPE_PROCESS_FLOW,
    CONTEXT_TYPE_DEPENDENCY,
    ALL_CONTEXT_TYPES,
    CONTEXT_SOURCE_DOCUMENT,
    CONTEXT_SOURCE_MANUAL,
    CONTEXT_SOURCE_API,
    CONTEXT_SOURCE_ANALYSIS,
    CONTEXT_SOURCE_PLATFORM,
)
from .project_version import (
    ProjectVersion,
    VERSION_STATUS_PLANNING,
    VERSION_STATUS_DEVELOPING,
    VERSION_STATUS_TESTING,
    VERSION_STATUS_READY_TO_RELEASE,
    VERSION_STATUS_RELEASED,
    VERSION_STATUS_ARCHIVED,
    ALL_VERSION_STATUSES,
)

# ============ Pydantic 请求模型 —— 实际放在 database/schemas/ 下 =========
# 这里只做 re-export，让历史 `from database.models import XxxCreate` 路径
# 不破。新代码请直接 `from database.schemas.xxx import ...`。
from database.schemas.config_update_item import ConfigUpdateItem
from database.schemas.project_create import ProjectCreate
from database.schemas.module_create import ModuleCreate
from database.schemas.test_case_create import TestCaseCreate
from database.schemas.run_test_request import RunTestRequest
from database.schemas.response_model import ResponseModel
from database.schemas.reorder_item import ReorderItem, ReorderRequest


__all__ = [
    # ORM models
    "Project", "Module",
    "TestCase", "TestStep",
    "FunctionalCaseRun", "ApiCaseEditHistory",
    "EditOperationBatch", "EditOperationEvent",
    "TestEnvironment", "TestVariable",
    "Device",
    "AppPackage",
    "TestReport", "TestStepReport",
    "ConfigStore", "ScriptStore",
    "AiRun", "Requirement", "RequirementAssignee", "RequirementVersionHistory",
    "RequirementEditHistory",
    "Attachment", "ATTACHMENT_KIND_LINK", "ATTACHMENT_KIND_FILE",
    "ALL_ATTACHMENT_KINDS",
    "RequirementAnalysisDocument", "RequirementAnalysisVersion",
    "AiCaseDraft",
    "AI_CASE_DRAFT_STATUS_PENDING", "AI_CASE_DRAFT_STATUS_ACCEPTED",
    "AI_CASE_DRAFT_STATUS_REJECTED", "ALL_AI_CASE_DRAFT_STATUSES",
    # AI Studio (M1)
    "AiDialogueSession",
    "AI_DIALOGUE_STATUS_ACTIVE", "AI_DIALOGUE_STATUS_FINALIZED",
    "AI_DIALOGUE_STATUS_ABANDONED", "ALL_AI_DIALOGUE_STATUSES",
    "AiRequirementDraft",
    "AI_REQ_DRAFT_STATUS_PENDING", "AI_REQ_DRAFT_STATUS_COMMITTED",
    "AI_REQ_DRAFT_STATUS_REJECTED", "ALL_AI_REQ_DRAFT_STATUSES",
    "CodingTask",
    "CODING_TASK_STATUS_QUEUED", "CODING_TASK_STATUS_INDEXING",
    "CODING_TASK_STATUS_GENERATING", "CODING_TASK_STATUS_APPLIED",
    "CODING_TASK_STATUS_FAILED", "CODING_TASK_STATUS_COMMITTED",
    "CODING_TASK_STATUS_PUSHED", "CODING_TASK_STATUS_REJECTED",
    "ALL_CODING_TASK_STATUSES",
    "CodeChunk", "DEFAULT_EMBEDDING_DIM",
    "TestPlan",
    "ProjectContext", "RequirementAnalysis",
    "ProjectVersion", "User",
    "VERSION_STATUS_READY_TO_RELEASE",
    "Role", "user_roles",
    "ROLE_ADMIN", "ROLE_DEV", "ROLE_TEST", "ROLE_PM", "ROLE_UI", "ROLE_OPS",
    "ALL_ROLE_CODES",
    "Task",
    "TASK_TYPE_DEV", "TASK_TYPE_TEST", "TASK_TYPE_UI_REVIEW",
    "TASK_TYPE_PM_REVIEW", "TASK_TYPE_BUG",
    "ALL_TASK_TYPES",
    "TASK_STATUS_PENDING", "TASK_STATUS_DEV_DOING", "TASK_STATUS_DEV_DONE",
    "TASK_STATUS_TEST_DOING", "TASK_STATUS_PASSED", "TASK_STATUS_FAILED",
    "TASK_STATUS_CLOSED", "ALL_TASK_STATUSES",
    "BUG_SEVERITY_P0", "BUG_SEVERITY_P1", "BUG_SEVERITY_P2", "BUG_SEVERITY_P3",
    "ALL_BUG_SEVERITIES",
    "VersionTestSummary",
    # Project context constants
    "CONTEXT_TYPE_BUSINESS_RULE", "CONTEXT_TYPE_DATA_MODEL",
    "CONTEXT_TYPE_API_CONTRACT", "CONTEXT_TYPE_ARCHITECTURE",
    "CONTEXT_TYPE_TERM_DEFINITION", "CONTEXT_TYPE_REQUIREMENT",
    "CONTEXT_TYPE_CONSTRAINT", "CONTEXT_TYPE_USER_SCENARIO",
    "CONTEXT_TYPE_PROCESS_FLOW", "CONTEXT_TYPE_DEPENDENCY",
    "ALL_CONTEXT_TYPES",
    "CONTEXT_SOURCE_DOCUMENT", "CONTEXT_SOURCE_MANUAL",
    "CONTEXT_SOURCE_API", "CONTEXT_SOURCE_ANALYSIS",
    "CONTEXT_SOURCE_PLATFORM",
    # Test plan constants
    "TEST_PLAN_STATUS_DRAFT", "TEST_PLAN_STATUS_PUBLISHED",
    "TEST_PLAN_STATUS_ARCHIVED", "ALL_TEST_PLAN_STATUSES",
    "TEST_PLAN_SOURCE_MANUAL", "TEST_PLAN_SOURCE_AI",
    # AI run status constants
    "AI_RUN_STATUS_PENDING", "AI_RUN_STATUS_RUNNING", "AI_RUN_STATUS_SUCCESS",
    "AI_RUN_STATUS_FAILED", "AI_RUN_STATUS_CANCELLED", "ALL_AI_RUN_STATUSES",
    # AI feature names
    "AI_FEATURE_REQUIREMENT_PARSE", "AI_FEATURE_TEST_PLAN",
    "AI_FEATURE_FUNCTIONAL_CASE_GEN", "AI_FEATURE_FUNCTIONAL_CASE_ENHANCE",
    "AI_FEATURE_FUNCTIONAL_CASE_REVIEW",
    "AI_FEATURE_API_CASE_GEN", "AI_FEATURE_REPORT_SUMMARY",
    "AI_FEATURE_FUNCTIONAL_TO_AUTO", "AI_FEATURE_LOAD_PLAN_GEN",
    "AI_FEATURE_BUG_FIX", "AI_FEATURE_API_REPORT_FIX",
    # Requirement constants
    "REQUIREMENT_STATUS_DRAFT", "REQUIREMENT_STATUS_APPROVED",
    "REQUIREMENT_STATUS_ARCHIVED", "ALL_REQUIREMENT_STATUSES",
    "REQUIREMENT_SOURCE_MANUAL", "REQUIREMENT_SOURCE_AI",
    "REQUIREMENT_SYSTEM_STATUS_APPROVED", "REQUIREMENT_SYSTEM_STATUS_DEVELOPING",
    "REQUIREMENT_SYSTEM_STATUS_TESTING", "REQUIREMENT_SYSTEM_STATUS_READY_TO_RELEASE",
    "REQUIREMENT_SYSTEM_STATUS_PM_REVIEW", "REQUIREMENT_SYSTEM_STATUS_DONE",
    "ALL_REQUIREMENT_SYSTEM_STATUSES",
    "REQUIREMENT_SYSTEM_STATUS_ORDER", "REQUIREMENT_SYSTEM_STATUS_TASK_DRIVEN",
    "REQUIREMENT_BUSINESS_STATUS_APPROVED", "REQUIREMENT_BUSINESS_STATUS_ACCEPTED",
    "REQUIREMENT_BUSINESS_STATUS_RELEASED", "ALL_REQUIREMENT_BUSINESS_STATUSES",
    # Requirement assignee / history
    "REQUIREMENT_ASSIGNEE_ROLE_DEV", "REQUIREMENT_ASSIGNEE_ROLE_TEST",
    "REQUIREMENT_ASSIGNEE_ROLE_PM", "REQUIREMENT_ASSIGNEE_ROLE_UI",
    "ALL_REQUIREMENT_ASSIGNEE_ROLES",
    "REQUIREMENT_VERSION_ACTION_PLAN", "REQUIREMENT_VERSION_ACTION_MOVE",
    "REQUIREMENT_VERSION_ACTION_REMOVE", "ALL_REQUIREMENT_VERSION_ACTIONS",
    # Project stack constants
    "PROJECT_STACK_API", "PROJECT_STACK_WEB",
    "PROJECT_STACK_ANDROID", "PROJECT_STACK_IOS",
    "PROJECT_STACK_FUNCTIONAL",
    "ALL_PROJECT_STACKS",
    # Case type constants
    "CASE_TYPE_API", "CASE_TYPE_ANDROID", "CASE_TYPE_IOS",
    "CASE_TYPE_WEB",
    "CASE_TYPE_MIXED", "CASE_TYPE_FUNCTIONAL",
    "ALL_CASE_TYPES", "APP_CASE_TYPES", "AUTOMATED_CASE_TYPES",
    # Functional run status constants
    "RUN_STATUS_PASSED", "RUN_STATUS_FAILED", "RUN_STATUS_BLOCKED",
    "RUN_STATUS_NA", "RUN_STATUS_PENDING", "ALL_RUN_STATUSES",
    "FunctionalCaseEditHistory",
    "EDIT_ACTION_CREATE", "EDIT_ACTION_UPDATE", "EDIT_ACTION_DELETE",
    "ALL_EDIT_ACTIONS",
    # Step type constants
    "STEP_TYPE_HTTP_REQUEST", "STEP_TYPE_SQL_QUERY", "STEP_TYPE_SCRIPT",
    "STEP_TYPE_APP_LAUNCH", "STEP_TYPE_APP_CLOSE",
    "STEP_TYPE_APP_TAP", "STEP_TYPE_APP_INPUT", "STEP_TYPE_APP_SWIPE",
    "STEP_TYPE_APP_PRESS", "STEP_TYPE_APP_WAIT",
    "STEP_TYPE_APP_SCREENSHOT", "STEP_TYPE_APP_BACK",
    "STEP_TYPE_WEB_GOTO", "STEP_TYPE_WEB_CLICK", "STEP_TYPE_WEB_INPUT",
    "STEP_TYPE_WEB_SELECT", "STEP_TYPE_WEB_WAIT",
    "STEP_TYPE_ASSERT", "STEP_TYPE_SLEEP",
    "ALL_STEP_TYPES",
    # Device status constants
    "DEVICE_STATUS_IDLE", "DEVICE_STATUS_BUSY", "DEVICE_STATUS_OFFLINE",
    # Pydantic (v1 遗留)
    "ProjectCreate", "ModuleCreate", "TestCaseCreate", "RunTestRequest",
    "ConfigUpdateItem", "ResponseModel", "ReorderItem", "ReorderRequest",
    # Script store constants
    "SCRIPT_KIND_FUNCTION", "SCRIPT_KIND_CRYPTO_REQUEST",
    "SCRIPT_KIND_CRYPTO_RESPONSE", "ALL_SCRIPT_KINDS",
    # Module outline
    "ModuleOutline", "ModuleOutlinePoint",
    "AiCaseFlag",
    "AI_FLAG_MANUAL_FIX", "AI_FLAG_INTERFACE_DEFECT", "AI_FLAG_ENVIRONMENT", "AI_FLAG_AI_FIXED",
    "ALL_AI_FLAG_TYPES",
    "AI_FLAG_STATUS_ACTIVE", "AI_FLAG_STATUS_CLEARED", "AI_FLAG_STATUS_AUTO_CLEARED",
    "AI_FLAG_STATUS_SUPERSEDED", "ALL_AI_FLAG_STATUSES",
    "AI_FLAG_REASON_MANUALLY_FIXED", "AI_FLAG_REASON_MISJUDGED",
    "AI_FLAG_REASON_EXTERNAL_FIXED", "AI_FLAG_REASON_WONT_FIX", "ALL_AI_FLAG_REASONS",
    "OUTLINE_POINT_COVERED", "OUTLINE_POINT_GAP", "OUTLINE_POINT_OBSOLETE",
    "ALL_OUTLINE_POINT_STATUSES",
    "OUTLINE_POINT_SOURCE_AI", "OUTLINE_POINT_SOURCE_MANUAL",
    "ALL_OUTLINE_POINT_SOURCES",
]
