"""knowledge dedicated tables

Revision ID: 83d3dbccee05
Revises: snapshot_module_id_001
Create Date: 2026-09-02 10:45:33.807477+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '83d3dbccee05'
down_revision: Union[str, None] = 'snapshot_module_id_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_folders_id'), 'knowledge_folders', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_folders_parent_id'), 'knowledge_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_folders_project_id'), 'knowledge_folders', ['project_id'], unique=False)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_kb_tag_project_name')
    )
    op.create_index(op.f('ix_knowledge_tags_id'), 'knowledge_tags', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_tags_project_id'), 'knowledge_tags', ['project_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('include_in_rag', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['knowledge_folders.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_folder_id'), 'knowledge_documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_module_id'), 'knowledge_documents', ['module_id'], unique=False)
    op.create_index('ix_knowledge_documents_project_folder', 'knowledge_documents', ['project_id', 'folder_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_project_id'), 'knowledge_documents', ['project_id'], unique=False)
    op.create_table('knowledge_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_attachments_document_id'), 'knowledge_attachments', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_attachments_id'), 'knowledge_attachments', ['id'], unique=False)
    op.create_table('knowledge_document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['knowledge_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('knowledge_document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_document_versions_document_id'), 'knowledge_document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_versions_id'), 'knowledge_document_versions', ['id'], unique=False)
    op.add_column('project_contexts', sa.Column('knowledge_document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_contexts_knowledge_document_id'), 'project_contexts', ['knowledge_document_id'], unique=False)
    op.create_foreign_key(
        'fk_project_contexts_knowledge_document_id',
        'project_contexts', 'knowledge_documents', ['knowledge_document_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_contexts_knowledge_document_id', 'project_contexts', type_='foreignkey')
    op.drop_index(op.f('ix_project_contexts_knowledge_document_id'), table_name='project_contexts')
    op.drop_column('project_contexts', 'knowledge_document_id')
    op.drop_index(op.f('ix_knowledge_document_versions_id'), table_name='knowledge_document_versions')
    op.drop_index(op.f('ix_knowledge_document_versions_document_id'), table_name='knowledge_document_versions')
    op.drop_table('knowledge_document_versions')
    op.drop_table('knowledge_document_tags')
    op.drop_index(op.f('ix_knowledge_attachments_id'), table_name='knowledge_attachments')
    op.drop_index(op.f('ix_knowledge_attachments_document_id'), table_name='knowledge_attachments')
    op.drop_table('knowledge_attachments')
    op.drop_index(op.f('ix_knowledge_documents_project_id'), table_name='knowledge_documents')
    op.drop_index('ix_knowledge_documents_project_folder', table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_module_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_folder_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_knowledge_tags_project_id'), table_name='knowledge_tags')
    op.drop_index(op.f('ix_knowledge_tags_id'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index(op.f('ix_knowledge_folders_project_id'), table_name='knowledge_folders')
    op.drop_index(op.f('ix_knowledge_folders_parent_id'), table_name='knowledge_folders')
    op.drop_index(op.f('ix_knowledge_folders_id'), table_name='knowledge_folders')
    op.drop_table('knowledge_folders')
    # ### end Alembic commands ###
